### PR TITLE
[#23] Rework SCI comparison

### PR DESCRIPTION
**Pull request by bsless**

### CODE REVIEW

**Comment by bsless** [comment]
@borkdude how does it look? Thinking of adding a few big "interesting" expressions

**Comment by borkdude** [comment]
@bsless Thanks!

A few things.

- Apart from the numbers, I'd like to change the framing of how contextual is a 2-phase interpreter and SCI is not: this is not correct, SCI has two distinct phases as well: analysis + evaluation. Unlike contextual SCI does not expose an intermediate representation, but you can evaluate functions that you can execute multiple times. These functions do not occupy  "metaspace" since there is no byte-code compilation involved in SCI either. Also the bodies of these functions are analyzed only once, not multiple times.

- Performance is a goal of SCI (within the constraints that it's usually used for: scripting within GraalVM-compiled or JS environments and I usually de-emphasize performance so people aren't too disappointed when they find out that compiled Clojure is much faster). So if there's anything that can be made faster, I or someone else will probably look into that as well (welcome to contribute!). As such, SCI should be benchmarked agains the latest version on master since it's a moving target and/or you should mention the git SHA of which SCI version you benchmarked against. Also it would be good to link to the benchmark docs in SCI to show how it should be benchmarked for fair comparison.

- Other than this, you should probably measure meaningful bigger programs for this benchmark to be meaningful in real applications?

**Comment by bsless** [comment]
@borkdude I think I removed all references to SCI's implementation details, but I can add clarifications
Also made sure to align to sci's latest Clojars release, but I don't mind adding these changes.
For bigger examples, I can target Contextual's use cases. If you want to suggest other cases, please do.
Did I run the benchmarks fairly?

**Comment by borkdude** [comment]
@bsless Ah sorry, I didn't see that. Yeah, I think the benchmarks are fair.

**Comment by bsless** [comment]
Anyway, @borkdude anything else you think needs changes here or are you satisfied with the new comparison, for now? Extra cases will take some time to cook up specifically

**Comment by borkdude** [comment]
Seems good to me, thanks!

**Pull request merged**
